apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reflector
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra-structure
  sources:
    - repoURL: https://emberstack.github.io/helm-charts
      chart: reflector
      targetRevision: 9.1.40
      helm:
        values: |
    - repoURL: https://github.com/lostady/k8s-infra
      path: reflector
      targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system  # Reflector is usually installed in system namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true

