apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-ingress
  namespace: minio-tenant
  annotations:
    nginx.ingress.kubernetes.io/whitelist-source-range: "61.77.247.3/32,125.246.87.242/32"
spec:
  ingressClassName: nginx

  tls:
    - hosts:
        - minio.archainia.app
      secretName: archainia-wildcard-tls

  rules:
    - host: minio.archainia.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio-tenant-shared-console
                port:
                  number: 9090

