apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra-structure
  # Argo CD Helm chart is manually installed (helm install)
  # This manages Argo CD resources only (ingress, etc.)
  source:
    repoURL: https://github.com/lostady/k8s-infra
    path: argo-cd
    targetRevision: main
    kustomize: {}  # Use kustomization.yaml (manage resources only)
  destination:
    server: https://kubernetes.default.svc
    namespace: default  # Deployed based on namespace defined in resources
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true


