apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longhorn-ui-ingress
  namespace: longhorn-system
  annotations:
    nginx.ingress.kubernetes.io/whitelist-source-range: "61.77.247.3/32,125.246.87.242/32"
spec:
  ingressClassName: nginx

  tls:
    - hosts:
        - longhorn.archainia.app
      secretName: archainia-wildcard-tls   # longhorn-system 네임스페이스에 있는 Secret

  rules:
    - host: longhorn.archainia.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: longhorn-frontend    # Longhorn UI 서비스 이름
                port:
                  number: 80